from __future__ import annotations

SYMBOL_UNIVERSE_DETAIL_LABELS = {
    "symbol": "銘柄コード",
    "name": "銘柄名",
    "market": "市場",
    "asset_type": "商品分類",
    "currency": "通貨",
    "broker": "取扱元",
    "tradability": "取引可否",
    "nisa_category": "NISA区分",
    "nisa_growth_eligible": "成長投資枠",
    "nisa_tsumitate_eligible": "つみたて投資枠",
    "investment_style": "投資スタイル",
    "is_sbi_supported": "SBI対応",
    "is_active": "有効銘柄",
    "is_leveraged": "レバレッジ",
    "is_inverse": "インバース",
    "theme": "テーマ",
    "sector": "セクター",
    "smai_theme_tags": "SMAIテーマタグ",
    "theme_source": "テーマ判定元",
    "theme_confidence": "テーマ信頼度",
    "tse_33_industry": "JPX 33業種",
    "topix_17": "TOPIX-17",
    "sector_gics": "GICSセクター",
    "industry_gics": "GICS業種",
    "subindustry_gics": "GICSサブ業種",
    "dividend_category": "配当カテゴリ",
    "dividend_yield_pct": "配当利回り(%)",
    "market_cap_tier": "時価総額分類",
    "index_family": "連動指数",
    "expense_ratio_pct": "信託報酬/経費率(%)",
    "complexity": "複雑さ",
    "risk_band": "値動きリスク",
    "per": "PER",
    "pbr": "PBR",
    "roe_pct": "ROE(%)",
    "consensus_rating": "コンセンサス",
    "forecast_agreement": "モデル一致度(補助)",
    "data_quality": "データ品質",
    "tags": "タグ",
    "aliases": "別名",
    "yahoo_symbol": "Yahoo取得用symbol",
    "yahoo_symbol_status": "Yahoo取得コード確認状態",
    "yahoo_symbol_checked_at": "Yahoo取得コード確認日",
    "yahoo_symbol_note": "Yahoo取得コードメモ",
    "metadata_source": "取得元情報",
    "metadata_as_of": "取得元情報の基準日",
    "metadata_updated_at": "取得元情報の更新日時",
    "symbol_cache_provider": "銘柄DB取得元",
    "symbol_cache_updated_at": "銘柄DB最終更新",
    "symbol_cache_source_as_of": "元データ基準日",
    "symbol_cache_source_updated_at": "元データ更新日時",
    "symbol_cache_last_price_updated_at": "価格データ更新",
    "symbol_cache_last_fundamental_updated_at": "財務データ更新",
    "symbol_cache_freshness_status": "銘柄DB鮮度",
}

SYMBOL_UNIVERSE_DISPLAY_LABELS = {
    "market": {"jp": "日本", "us": "米国", "all": "すべて"},
    "asset_type": {
        "stock": "個別株",
        "etf": "ETF",
        "reit": "REIT",
        "mutual_fund": "投資信託",
        "adr": "ADR",
    },
    "broker": {"sbi_securities": "SBI証券", "unknown": "未確認"},
    "tradability": {
        "tradable": "取引可能",
        "not_tradable": "取引対象外",
        "unknown": "未確認",
    },
    "nisa_category": {
        "growth": "成長投資枠",
        "tsumitate": "つみたて投資枠",
        "both": "成長投資枠・つみたて投資枠",
        "none": "NISA対象外",
        "unknown": "未確認",
    },
    "investment_style": {
        "lump_sum": "一括投資向き",
        "recurring": "積立向き",
        "both": "一括・積立どちらも対象",
        "unknown": "未確認",
    },
    "sector": {
        "communication": "通信・メディア",
        "consumer": "消費財・サービス",
        "energy": "エネルギー",
        "financial": "金融",
        "healthcare": "ヘルスケア",
        "index": "インデックス",
        "industrial": "工業・資本財",
        "materials": "素材",
        "real_estate": "不動産",
        "technology": "テクノロジー",
        "utilities": "公益",
    },
    "complexity": {
        "beginner": "初心者向け",
        "standard": "標準",
        "advanced": "上級者向け",
        "currency_select": "通貨選択型",
        "etn": "ETN",
        "inverse": "インバース",
        "leveraged": "レバレッジ",
        "thematic": "テーマ型",
    },
    "risk_band": {
        "LOW": "低め",
        "MEDIUM": "標準",
        "HIGH": "高め",
    },
    "forecast_agreement": {"HIGH": "高い", "MEDIUM": "中くらい", "LOW": "低い"},
    "data_quality": {"OK": "十分", "WARN": "一部不足", "BLOCK": "不足が大きい"},
    "metadata_source": {
        "curated_csv": "手動整備CSV",
        "csv": "ローカルCSV",
        "fsa": "金融庁/NISA情報",
        "imaj": "投資信託協会",
        "jpx": "JPX公式情報",
        "jpx_listed_stock": "JPX上場銘柄情報",
        "jpx_nisa_growth": "JPX NISA成長投資枠リスト",
        "jpx_reit": "JPX REIT情報",
        "manual": "手動整備",
        "mutual_fund_seed": "投資信託初期データ",
        "sbi_us_etf": "SBI証券 米国ETF取扱銘柄",
        "sbi_us_stock": "SBI証券 米国株取扱銘柄",
        "yahoo": "Yahoo Finance",
        "unknown": "未確認",
    },
    "management_style": {"index": "インデックス", "active": "アクティブ"},
    "distribution_policy": {
        "none": "分配なし",
        "monthly": "毎月",
        "quarterly": "四半期",
        "semiannual": "年2回",
        "annual": "年1回",
        "irregular": "不定期",
    },
}

SYMBOL_UNIVERSE_NISA_SHORT_LABELS = {
    "成長投資枠・つみたて投資枠": "両枠",
    "つみたて投資枠": "つみたて枠",
}

SYMBOL_UNIVERSE_RISK_BAND_SHORT_LABELS = {
    "LOW": "低変動",
    "MEDIUM": "標準",
    "HIGH": "高変動",
}
