from __future__ import annotations

import argparse
import csv
import sys
from datetime import datetime
from decimal import Decimal, InvalidOperation
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))


REQUIRED_COLUMNS = {
    "symbol",
    "market",
    "asset_type",
    "regime",
    "model_name",
    "horizon_days",
    "origin_at",
    "target_at",
    "predicted_return",
    "actual_return",
}


def main(argv: list[str] | None = None) -> int:
    from backend.forecast.evaluation import ForecastValidationPoint
    from backend.scoring.upward_signal_forecast_integration import (
        evaluate_forecast_validation_points,
        write_forecast_validation_outputs,
    )

    parser = argparse.ArgumentParser(
        description="Evaluate Upward Signal forecast integration from point-in-time CSV data."
    )
    parser.add_argument(
        "--validation-csv",
        default="reports/phase34_forecast_validation/forecast_model_validation_points.csv",
        help="Existing forecast_model_validation_points.csv generated by the forecast evaluator.",
    )
    parser.add_argument("--output", default="reports/upward_signal_forecast_integration")
    args = parser.parse_args(argv)

    try:
        points = _read_validation_points(Path(args.validation_csv), ForecastValidationPoint)
    except (OSError, ValueError) as exc:
        print(f"Unable to read validation CSV: {exc}", file=sys.stderr)
        return 2
    cases = evaluate_forecast_validation_points(points)
    paths = write_forecast_validation_outputs(cases, Path(args.output))
    print(f"validation points: {len(points)}")
    print(f"consensus origin cases: {len(cases)}")
    for name, path in paths.items():
        print(f"{name}: {path}")
    if not cases:
        print("No complete consensus origins were found; no adoption conclusion is available.")
    return 0


def _read_validation_points(path: Path, model_type: type) -> list:
    with path.open("r", encoding="utf-8-sig", newline="") as handle:
        reader = csv.DictReader(handle)
        columns = set(reader.fieldnames or ())
        missing = REQUIRED_COLUMNS - columns
        if missing:
            raise ValueError(f"missing required columns: {', '.join(sorted(missing))}")
        points = []
        for line_number, row in enumerate(reader, start=2):
            try:
                points.append(
                    model_type(
                        symbol=_required(row, "symbol"),
                        market=_required(row, "market"),
                        asset_type=_required(row, "asset_type"),
                        regime=_required(row, "regime"),
                        model_name=_required(row, "model_name"),
                        horizon_days=int(_required(row, "horizon_days")),
                        origin_at=_parse_datetime(_required(row, "origin_at")),
                        target_at=_parse_datetime(_required(row, "target_at")),
                        predicted_return=_decimal(row, "predicted_return"),
                        actual_return=_decimal(row, "actual_return"),
                        model_disagreement=_optional_decimal(row.get("model_disagreement")),
                    )
                )
            except (TypeError, ValueError, InvalidOperation) as exc:
                raise ValueError(f"invalid row {line_number}: {exc}") from exc
    return points


def _required(row: dict[str, str | None], name: str) -> str:
    value = (row.get(name) or "").strip()
    if not value:
        raise ValueError(f"{name} is empty")
    return value


def _decimal(row: dict[str, str | None], name: str) -> Decimal:
    return Decimal(_required(row, name))


def _optional_decimal(value: str | None) -> Decimal | None:
    if value is None or not value.strip():
        return None
    return Decimal(value)


def _parse_datetime(value: str) -> datetime:
    return datetime.fromisoformat(value.strip().replace("Z", "+00:00"))


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
